name: Run phpunit test suite

on:
  push:
  pull_request:
  schedule:
    - cron: '0 * * * *'

jobs:
  phpunit-test-suite:
    uses: juzaweb/actions/.github/workflows/plugin-test.yml@main
    with:
      vendor: juzaweb
      plugin: subscription
      #version: dev-${{ github.head_ref || github.ref_name }}
